export const countriesDictionary = {
	'Afeganistão': 'Afghanistan',
	'África do Sul': 'South Africa',
	'Albânia': 'Albania',
	'Alemanha': 'Germany',
	'Andorra': 'Andorra',
	'Angola': 'Angola',
	'Anguila': 'Anguilla',
	'Antilhas Holandesas': 'Netherlands Antilles',
	'Antárctida': 'Antarctica',
	'Antígua e Barbuda': 'Antigua and Barbuda',
	'Argentina': 'Argentina',
	'Argélia': 'Algeria',
	'Arménia': 'Armenia',
	'Aruba': 'Aruba',
	'Arábia Saudita': 'Saudi Arabia',
	'Austrália': 'Australia',
	'Áustria': 'Austria',
	'Azerbaijão': 'Azerbaijan',
	'Bahamas': 'Bahamas',
	'Bangladeche': 'Bangladesh',
	'Barbados': 'Barbados',
	'Barém': 'Bahrain',
	'Belize': 'Belize',
	'Benim': 'Benin',
	'Bermudas': 'Bermuda',
	'Bielorrússia': 'Belarus',
	'Bolívia': 'Bolivia, Plurinational State of Bolivia',
	'Botsuana': 'Botswana',
	'Brasil': 'Brazil',
	'Brunei': 'Brunei Darussalam',
	'Bulgária': 'Bulgaria',
	'Burquina Faso': 'Burkina Faso',
	'Burúndi': 'Burundi',
	'Butão': 'Bhutan',
	'Bélgica': 'Belgium',
	'Bósnia e Herzegovina': 'Bosnia and Herzegovina',
	'Cabo Verde': 'Cape Verde',
	'Camarões': 'Cameroon',
	'Camboja': 'Cambodia',
	'Canadá': 'Canada',
	'Catar': 'Qatar',
	'Cazaquistão': 'Kazakhstan',
	'Chade': 'Chad',
	'Chile': 'Chile',
	'China': 'China',
	'Chipre': 'Cyprus',
	'Colômbia': 'Colombia',
	'Comores': 'Comoros',
	'Congo-Brazzaville': 'Congo',
	'Congo-Kinshasa': 'Congo, The Democratic Republic of the',
	'Coreia do Norte': 'Korea, Republic of',
	'Coreia do Sul': "Korea, Democratic People's Republic of",
	'Costa Rica': 'Costa Rica',
	'Costa do Marfim': "Cote d'Ivoire",
	'Croácia': 'Croatia',
	'Cuba': 'Cuba',
	'Dinamarca': 'Denmark',
	'Domínica': 'Dominica',
	'Egipto': 'Egypt',
	'El Salvador': 'El Salvador',
	'Emiratos Árabes Unidos': 'United Arab Emirates',
	'Equador': 'Ecuador',
	'Eritreia': 'Eritrea',
	'Eslováquia': 'Slovakia',
	'Eslovénia': 'Slovenia',
	'Espanha': 'Spain',
	'Estados Unidos': 'United States',
	'Estónia': 'Estonia',
	'Etiópia': 'Ethiopia',
	'Faroé': 'Faroe Islands',
	'Fiji': 'Fiji',
	'Filipinas': 'Philippines',
	'Finlândia': 'Finland',
	'França': 'France',
	'Gabão': 'Gabon',
	'Gana': 'Ghana',
	'Geórgia': 'Georgia',
	'Geórgia do Sul e Ilhas Sandwich do Sul': 'South Georgia and the South Sandwich Islands',
	'Gibraltar': 'Gibraltar',
	'Granada': 'Grenada',
	'Gronelândia': 'Greenland',
	'Grécia': 'Greece',
	'Guadalupe': 'Guadeloupe',
	'Guame': 'Guam',
	'Guatemala': 'Guatemala',
	'Guernsey': 'Guernsey',
	'Guiana': 'Guyana',
	'Guiana Francesa': 'French Guiana',
	'Guiné': 'Guinea',
	'Guiné Equatorial': 'Equatorial Guinea',
	'Guiné-Bissau': 'Guinea-Bissau',
	'Gâmbia': 'Gambia',
	'Haiti': 'Haiti',
	'Honduras': 'Honduras',
	'Hong Kong': 'Hong Kong',
	'Hungria': 'Hungary',
	'Iémen': 'Yemen',
	'Ilha Bouvet': 'Bouvet Island',
	'Ilha Norfolk': 'Norfolk Island',
	'Ilha do Natal': 'Christmas Island',
	'Ilhas Caimão': 'Cayman Islands',
	'Ilhas Cook': 'Cook Islands',
	'Ilhas Falkland': 'Falkland Islands (Malvinas)',
	'Ilhas Heard e McDonald': 'Heard Island and McDonald Islands',
	'Ilhas Marshall': 'Marshall Islands',
	'Ilhas Menores Distantes dos Estados Unidos': 'United States Minor Outlying Islands',
	'Ilhas Salomão': 'Solomon Islands',
	'Ilhas Turcas e Caicos': 'Turks and Caicos Islands',
	'Ilhas Virgens Americanas': 'Virgin Islands, U.S.',
	'Ilhas Virgens Britânicas': 'Virgin Islands, British',
	'Ilhas dos Cocos': 'Cocos (Keeling) Islands',
	'Índia': 'India',
	'Indonésia': 'Indonesia',
	'Irão': 'Iran, Islamic Republic of',
	'Iraque': 'Iraq',
	'Irlanda': 'Ireland',
	'Islândia': 'Iceland',
	'Israel': 'Israel',
	'Itália': 'Italy',
	'Jamaica': 'Jamaica',
	'Japão': 'Japan',
	'Jersey': 'Jersey',
	'Jibuti': 'Djibouti',
	'Jordânia': 'Jordan',
	'Kuwait': 'Kuwait',
	'Laos': "Lao People's Democratic Republic",
	'Lesoto': 'Lesotho',
	'Letónia': 'Latvia',
	'Libéria': 'Liberia',
	'Listenstaine': 'Liechtenstein',
	'Lituânia': 'Lithuania',
	'Luxemburgo': 'Luxembourg',
	'Líbano': 'Lebanon',
	'Líbia': 'Libyan Arab Jamahiriya',
	'Macau': 'Macao',
	'Macedónia': 'Macedonia, The Former Yugoslav Republic of',
	'Madagáscar': 'Madagascar',
	'Maldivas': 'Maldives',
	'Mali': 'Mali',
	'Malta': 'Malta',
	'Malásia': 'Malaysia',
	'Malávi': 'Malawi',
	'Man, Isle of': 'Isle of Man',
	'Marianas do Norte': 'Northern Mariana Islands',
	'Marrocos': 'Morocco',
	'Martinica': 'Martinique',
	'Mauritânia': 'Mauritania',
	'Maurícia': 'Mauritius',
	'Mayotte': 'Mayotte',
	'Micronésia': 'Micronesia, Federated States of',
	'Moldávia': 'Moldova, Republic of',
	'Mongólia': 'Mongolia',
	'Monserrate': 'Montserrat',
	'Montenegro': 'Montenegro',
	'Moçambique': 'Mozambique',
	'Myanmar': 'Myanmar',
	'México': 'Mexico',
	'Mónaco': 'Monaco',
	'Namíbia': 'Namibia',
	'Nauru': 'Nauru',
	'Nepal': 'Nepal',
	'Nicarágua': 'Nicaragua',
	'Nigéria': 'Nigeria',
	'Niue': 'Niue',
	'Noruega': 'Norway',
	'Nova Caledónia': 'New Caledonia',
	'Nova Zelândia': 'New Zealand',
	'Níger': 'Niger',
	'Omã': 'Oman',
	'Palau': 'Palau',
	'Panamá': 'Panama',
	'Papua-Nova Guiné': 'Papua New Guinea',
	'Paquistão': 'Pakistan',
	'Paraguai': 'Paraguay',
	'Países Baixos': 'Netherlands',
	'Peru': 'Peru',
	'Pitcairn': 'Pitcairn',
	'Polinésia Francesa': 'French Polynesia',
	'Polónia': 'Poland',
	'Porto Rico': 'Puerto Rico',
	'Portugal': 'Portugal',
	'Quirguizistão': 'Kyrgyzstan',
	'Quiribáti': 'Kiribati',
	'Quénia': 'Kenya',
	'Reino Unido': 'United Kingdom',
	'República Centro-Africana': 'Central African Republic',
	'República Checa': 'Czech Republic',
	'República Dominicana': 'Dominican Republic',
	'Reunião': 'Réunion',
	'Roménia': 'Romania',
	'Ruanda': 'Rwanda',
	'Rússia': 'Russia',
	'Samoa': 'Samoa',
	'Samoa Americana': 'AmericanSamoa',
	'Santa Helena': 'Saint Helena, Ascension and Tristan Da Cunha',
	'Santa Lúcia': 'Saint Lucia',
	'Sara Ocidental': 'Western Sahara',
	'Seicheles': 'Seychelles',
	'Senegal': 'Senegal',
	'Serra Leoa': 'Sierra Leone',
	'Singapura': 'Singapore',
	'Somália': 'Somalia',
	'Sri Lanca': 'Sri Lanka',
	'Suazilândia': 'Swaziland',
	'Sudão': 'Sudan',
	'Suriname': 'Suriname',
	'Suécia': 'Sweden',
	'Suíça': 'Switzerland',
	'Svalbard e Jan Mayen': 'Svalbard and Jan Mayen',
	'São Cristóvão e Neves': 'Saint Kitts and Nevis',
	'São Marinho': 'San Marino',
	'São Pedro e Miquelon': 'Saint Pierre and Miquelon',
	'São Tomé e Príncipe': 'Sao Tome and Principe',
	'São Vicente e Granadinas': 'Saint Vincent and the Grenadines',
	'Sérvia': 'Serbia',
	'Síria': 'Syrian Arab Republic',
	'Tailândia': 'Thailand',
	'Taiwan': 'Taiwan',
	'Tajiquistão': 'Tajikistan',
	'Tanzânia': 'Tanzania, United Republic of',
	'Território Britânico do Oceano Índico': 'British Indian Ocean Territory',
	'Territórios Austrais Franceses': 'French Southern and Antarctic Lands',
	'Territórios Palestinos': 'Palestinian Territory, Occupied',
	'Timor Leste': 'Timor-Leste',
	'Togo': 'Togo',
	'Tokelau': 'Tokelau',
	'Tonga': 'Tonga',
	'Trindade e Tobago': 'Trinidad and Tobago',
	'Tunísia': 'Tunisia',
	'Turquemenistão': 'Turkmenistan',
	'Turquia': 'Turkey',
	'Tuvalu': 'Tuvalu',
	'Ucrânia': 'Ukraine',
	'Uganda': 'Uganda',
	'Uruguai': 'Uruguay',
	'Usbequistão': 'Uzbekistan',
	'Vanuatu': 'Vanuatu',
	'Vaticano': 'Holy See (Vatican City State)',
	'Venezuela': 'Venezuela, Bolivarian Republic of',
	'Vietname': 'Viet Nam',
	'Wallis e Futuna': 'Wallis and Futuna',
	'Zimbabué': 'Zimbabwe',
	'Zâmbia': 'Zambia',
};

export const allCountriesPortuguese = Object.keys(countriesDictionary).sort((a, b) =>
	a.localeCompare(b),
);
